sudo: required
language: generic

services:
  - docker

before_install:
  - docker build -t naveejr/docker-react -f Dockerfile.dev .



script:
  - docker run -e CI=true naveejr/docker-react npm run test
