FROM node:alpine
USER node

ENV NPM_CONFIG_PREFIX=/home/node/.npm-global
ENV PATH=$PATH:/home/node/.npm-global/bin

WORKDIR '/home/node'

COPY package.json .
RUN npm install

COPY . .
CMD ["npm", "run", "start"]
